tags_list_pnet = ['id',
 'shm_krn',
 'taarich_hafakat_hadoch',
 'sug_krn',
 'shm_taagid_sholet',
 'sug_taagid_sholet',
 'tkufat_divuach',
 'hafkadot_llo_haavarot',
 'mshichot_llo_haavarot',
 'haavarot_bein_hakupot',
 'tzvira_neto',
 'yitrat_nchasim_lsof_tkufa',
 'shiur_dmei_nihul_aharon',
 'tsua_nominalit_bruto_hodshit',
 'tsua_mitzt_mi_thilat_shana',
 'tsua_memuzaat_36_hodashim',
 'tsua_memuzaat_60_hodashim',
 'tsua_mitztaberet_36_hodashim',
 'tsua_mitztaberet_60_hodashim',
 'tsua_shnatit_memuzaat_3_shanim',
 'tsua_shnatit_memuzaat_5_shanim',
 'stiat_teken_36_hodashim',
 'stiat_teken_60_hodashim',
 'matzav_divuach',
 'alpha_shnati',
 'beta_ta100',
 'beta_agach_kontzerniot_tzmudot',
 'beta_agach_mem_lo_tzmudot',
 'beta_agach_memshaltiot_tzmudot',
 'beta_hutz_laaretz',
 'r_squared',
 'sharp_tsua_hetzyonit_anaf',
 'sharp_tsua_hetzyonit_all',
 'sharp_ribit_hasrat_sikun',
 'yahas_nezilut',
 'shm_hevra_menahelet',
 'shiur_d_nihul_aharon_hafkadot',
 'shiur_d_nihul_aharon_nchasim',
 'odef_giraon_actuari_aharon',
 'yr_odef_giraon_actuari_aharon',
 'odef_giraon_actuari_letkufa',
 'tsua_nom_hashkaot_hofshiot',
 'num_hevra',
 'taarich_sium_peilut',
 'id_maslul_rishuy']


tags_list_gnet = ['id',
 'shm_kupa',
 'taarich_hafakat_hadoch',
 'sug_kupa',
 'shm_taagid_sholet',
 'sug_taagid_sholet',
 'shm_hevra_menahelet',
 'taarich_hakama',
 'uchlusiyat_yaad',
 'hitmahut_rashit',
 'hitmahut_mishnit',
 'tkufat_divuach',
 'hafkadot_llo_haavarot',
 'mshichot_llo_haavarot',
 'haavarot_bein_hakupot',
 'tzvira_neto',
 'yitrat_nchasim_lsof_tkufa',
 'shiur_dmei_nihul_aharon',
 'shiur_d_nihul_aharon_hafkadot',
 'tsua_nominalit_bruto_hodshit',
 'tsua_mitzt_mi_thilat_shana',
 'tsua_memuzaat_36_hodashim',
 'tsua_memuzaat_60_hodashim',
 'tsua_mitztaberet_36_hodashim',
 'tsua_mitztaberet_60_hodashim',
 'tsua_shnatit_memuzaat_3_shanim',
 'tsua_shnatit_memuzaat_5_shanim',
 'stiat_teken_36_hodashim',
 'stiat_teken_60_hodashim',
 'matzav_divuach',
 'alpha_shnatit',
 'sharp_anaf',
 'sharp_kol_hakupot',
 'sharp_ribit_hasrat_sikun',
 'yahas_nezilut',
 'mispar_kupa_av',
 'num_hevra']

tags_list_pnet_perut = ['id_krn','shm_krn','tkf_divuach','id_natun','shm_krn','erech_natun','achuz']

tags_list_gnet_perut = ['id_kupa','tkf_divuach','id_natun','shm_natun','erech_natun','achuz']

